--[[
name:Loader
fullname:Spindle.Loader
description:Loader Module Script (Will be auto generated by BASH Application)
fulldescription:This module loads all required modules. Normally it will be generated by a bash application.
extends:
depends:
author:Kagu-chan
version:1.0
type:module
docExternal:https://github.com/Kagurame/AegiSpindle/tree/master/doc/core/loader.md
docInternal:
	
]]

-- Set global functions and objects to local cache for performance
local Spindle = _G.Spindle or {}

Spindle.modules.load("type")
Spindle.modules.load("config")
Spindle.modules.load("cache")
Spindle.modules.load("table")
Spindle.modules.load("oop")
Spindle.modules.load("ffi")
Spindle.modules.load("ffi_os")
Spindle.modules.load("text")
Spindle.modules.load("utf8")
Spindle.modules.load("utf8_ffi")
Spindle.modules.load("math")
Spindle.modules.load("vectors")
Spindle.modules.load("matrix")
Spindle.modules.load("shape")
Spindle.modules.load("fileutils")
Spindle.modules.load("math_vectors")
Spindle.modules.load("git_doc")