--[[
name:Loader
description:Loader Module Script (Will be auto generated by BASH Application)
extends:
depends:
author:Kagu-chan
version:1.0
type:module
docExternal:https://github.com/Kagurame/AegiSpindle/tree/master/doc/core/loader.md
docInternal:
	
]]

Spindle.modules.load("type")
Spindle.modules.load("config")
Spindle.modules.load("cache")
Spindle.modules.load("ffi")
Spindle.modules.load("table")
Spindle.modules.load("text")
Spindle.modules.load("utf8")
Spindle.modules.load("utf8_ffi")
Spindle.modules.load("math")
Spindle.modules.load("oop")
Spindle.modules.load("vectors")
Spindle.modules.load("math_vectors")